"""Initial database schema

Revision ID: 58cd5e96ee43
Revises: 
Create Date: 2025-12-14 09:19:35.080778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cd5e96ee43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_group_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age_min', sa.Float(), nullable=False),
    sa.Column('age_max', sa.Float(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('vision_model', sa.String(), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('age_years', sa.Float(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('expert_label', sa.String(), nullable=True),
    sa.Column('drawing_tool', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('age_group_model_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('normalized_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('analysis_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['age_group_model_id'], ['age_group_models.id'], ),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawing_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('embedding_vector', sa.LargeBinary(), nullable=False),
    sa.Column('vector_dimension', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interpretability_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('saliency_map_path', sa.String(), nullable=False),
    sa.Column('overlay_image_path', sa.String(), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('importance_regions', sa.Text(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['anomaly_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interpretability_results')
    op.drop_table('drawing_embeddings')
    op.drop_table('anomaly_analyses')
    op.drop_table('drawings')
    op.drop_table('age_group_models')
    # ### end Alembic commands ###