"""add_subject_aware_architecture_columns

Revision ID: 9eec035faf01
Revises: b664dfddcaf9
Create Date: 2025-12-17 21:40:52.206344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eec035faf01'
down_revision = 'b664dfddcaf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values for existing records
    op.add_column('age_group_models', sa.Column('supports_subjects', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('age_group_models', sa.Column('subject_categories', sa.Text(), nullable=True))
    op.add_column('age_group_models', sa.Column('embedding_type', sa.String(), nullable=False, server_default='hybrid'))
    op.add_column('anomaly_analyses', sa.Column('visual_anomaly_score', sa.Float(), nullable=True))
    op.add_column('anomaly_analyses', sa.Column('subject_anomaly_score', sa.Float(), nullable=True))
    op.add_column('anomaly_analyses', sa.Column('anomaly_attribution', sa.String(), nullable=True))
    op.add_column('anomaly_analyses', sa.Column('analysis_type', sa.String(), nullable=False, server_default='subject_aware'))
    op.add_column('drawing_embeddings', sa.Column('embedding_type', sa.String(), nullable=False, server_default='hybrid'))
    op.add_column('drawing_embeddings', sa.Column('visual_component', sa.LargeBinary(), nullable=True))
    op.add_column('drawing_embeddings', sa.Column('subject_component', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawing_embeddings', 'subject_component')
    op.drop_column('drawing_embeddings', 'visual_component')
    op.drop_column('drawing_embeddings', 'embedding_type')
    op.drop_column('anomaly_analyses', 'analysis_type')
    op.drop_column('anomaly_analyses', 'anomaly_attribution')
    op.drop_column('anomaly_analyses', 'subject_anomaly_score')
    op.drop_column('anomaly_analyses', 'visual_anomaly_score')
    op.drop_column('age_group_models', 'embedding_type')
    op.drop_column('age_group_models', 'subject_categories')
    op.drop_column('age_group_models', 'supports_subjects')
    # ### end Alembic commands ###