"""Add training job and report models

Revision ID: b664dfddcaf9
Revises: 58cd5e96ee43
Create Date: 2025-12-14 23:15:13.286569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b664dfddcaf9'
down_revision = '58cd5e96ee43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('config_parameters', sa.Text(), nullable=False),
    sa.Column('dataset_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('end_timestamp', sa.DateTime(), nullable=True),
    sa.Column('sagemaker_job_arn', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_job_id', sa.Integer(), nullable=False),
    sa.Column('final_loss', sa.Float(), nullable=False),
    sa.Column('validation_accuracy', sa.Float(), nullable=False),
    sa.Column('best_epoch', sa.Integer(), nullable=False),
    sa.Column('training_time_seconds', sa.Float(), nullable=False),
    sa.Column('model_parameters_path', sa.String(), nullable=False),
    sa.Column('metrics_summary', sa.Text(), nullable=False),
    sa.Column('report_file_path', sa.String(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_reports')
    op.drop_table('training_jobs')
    # ### end Alembic commands ###