"""
Database models for the Children's Drawing Anomaly Detection System.

This module contains SQLAlchemy models for storing drawings, embeddings,
age group models, anomaly analyses, and interpretability results.
"""

from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    LargeBinary,
    String,
    Text,
)
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


def utc_now():
    """Get current UTC timestamp."""
    return datetime.now(timezone.utc)


class Drawing(Base):
    """Model for storing drawing metadata and file information."""

    __tablename__ = "drawings"

    id = Column(Integer, primary_key=True)
    filename = Column(String, nullable=False)
    file_path = Column(String, nullable=False)
    age_years = Column(Float, nullable=False)
    subject = Column(String, nullable=True)
    expert_label = Column(String, nullable=True)  # "normal", "concern", "severe"
    drawing_tool = Column(String, nullable=True)
    prompt = Column(Text, nullable=True)
    upload_timestamp = Column(DateTime, default=utc_now)

    # Relationships
    embeddings = relationship(
        "DrawingEmbedding", back_populates="drawing", cascade="all, delete-orphan"
    )
    analyses = relationship(
        "AnomalyAnalysis", back_populates="drawing", cascade="all, delete-orphan"
    )


class DrawingEmbedding(Base):
    """Model for storing drawing embeddings generated by vision models."""

    __tablename__ = "drawing_embeddings"

    id = Column(Integer, primary_key=True)
    drawing_id = Column(Integer, ForeignKey("drawings.id"), nullable=False)
    model_type = Column(String, nullable=False)  # "vit"
    embedding_type = Column(
        String, nullable=False, default="hybrid"
    )  # Always "hybrid" for subject-aware system
    embedding_vector = Column(
        LargeBinary, nullable=False
    )  # Serialized numpy array (832 dimensions)
    visual_component = Column(
        LargeBinary, nullable=True
    )  # Visual embedding component (768 dimensions)
    subject_component = Column(
        LargeBinary, nullable=True
    )  # Subject encoding component (64 dimensions)
    vector_dimension = Column(
        Integer, nullable=False, default=832
    )  # Always 832 for hybrid embeddings
    created_timestamp = Column(DateTime, default=utc_now)

    # Relationships
    drawing = relationship("Drawing", back_populates="embeddings")


class AgeGroupModel(Base):
    """Model for storing age-specific autoencoder models and their parameters."""

    __tablename__ = "age_group_models"

    id = Column(Integer, primary_key=True)
    age_min = Column(Float, nullable=False)
    age_max = Column(Float, nullable=False)
    model_type = Column(String, nullable=False)  # "autoencoder"
    vision_model = Column(String, nullable=False)  # "vit"
    supports_subjects = Column(
        Boolean, nullable=False, default=True
    )  # Always True for subject-aware system
    subject_categories = Column(
        Text, nullable=True
    )  # JSON array of supported subject categories
    embedding_type = Column(
        String, nullable=False, default="hybrid"
    )  # Always "hybrid" for subject-aware system
    parameters = Column(Text, nullable=False)  # JSON serialized parameters
    sample_count = Column(Integer, nullable=False)
    threshold = Column(Float, nullable=False)
    created_timestamp = Column(DateTime, default=utc_now)
    is_active = Column(Boolean, default=True)

    # Relationships
    analyses = relationship("AnomalyAnalysis", back_populates="age_group_model")


class AnomalyAnalysis(Base):
    """Model for storing anomaly analysis results for drawings."""

    __tablename__ = "anomaly_analyses"

    id = Column(Integer, primary_key=True)
    drawing_id = Column(Integer, ForeignKey("drawings.id"), nullable=False)
    age_group_model_id = Column(
        Integer, ForeignKey("age_group_models.id"), nullable=False
    )
    anomaly_score = Column(Float, nullable=False)  # Overall reconstruction loss
    normalized_score = Column(Float, nullable=False)  # Normalized to 0-1 range
    visual_anomaly_score = Column(
        Float, nullable=True
    )  # Visual component reconstruction loss (dims 0-767)
    subject_anomaly_score = Column(
        Float, nullable=True
    )  # Subject component reconstruction loss (dims 768-831)
    anomaly_attribution = Column(
        String, nullable=True
    )  # "subject", "visual", "both", or "age" (from cross-model comparison)
    analysis_type = Column(
        String, nullable=False, default="subject_aware"
    )  # Always "subject_aware"
    is_anomaly = Column(Boolean, nullable=False)
    confidence = Column(Float, nullable=False)
    analysis_timestamp = Column(DateTime, default=utc_now)

    # Relationships
    drawing = relationship("Drawing", back_populates="analyses")
    age_group_model = relationship("AgeGroupModel", back_populates="analyses")
    interpretability = relationship(
        "InterpretabilityResult",
        back_populates="analysis",
        cascade="all, delete-orphan",
    )


class InterpretabilityResult(Base):
    """Model for storing interpretability results including saliency maps and explanations."""

    __tablename__ = "interpretability_results"

    id = Column(Integer, primary_key=True)
    analysis_id = Column(Integer, ForeignKey("anomaly_analyses.id"), nullable=False)
    saliency_map_path = Column(String, nullable=False)
    overlay_image_path = Column(String, nullable=False)
    explanation_text = Column(Text, nullable=True)
    importance_regions = Column(Text, nullable=True)  # JSON serialized bounding boxes
    created_timestamp = Column(DateTime, default=utc_now)

    # Relationships
    analysis = relationship("AnomalyAnalysis", back_populates="interpretability")


class TrainingJob(Base):
    """Model for storing training job information and status."""

    __tablename__ = "training_jobs"

    id = Column(Integer, primary_key=True)
    job_name = Column(String, nullable=False)
    environment = Column(String, nullable=False)  # "local", "sagemaker"
    config_parameters = Column(Text, nullable=False)  # JSON serialized training config
    dataset_path = Column(String, nullable=False)
    status = Column(
        String, nullable=False
    )  # "pending", "running", "completed", "failed"
    start_timestamp = Column(DateTime, nullable=True)
    end_timestamp = Column(DateTime, nullable=True)
    sagemaker_job_arn = Column(String, nullable=True)  # For SageMaker jobs

    # Relationships
    training_reports = relationship(
        "TrainingReport", back_populates="training_job", cascade="all, delete-orphan"
    )


class TrainingReport(Base):
    """Model for storing training results and performance metrics."""

    __tablename__ = "training_reports"

    id = Column(Integer, primary_key=True)
    training_job_id = Column(Integer, ForeignKey("training_jobs.id"), nullable=False)
    final_loss = Column(Float, nullable=False)
    validation_accuracy = Column(Float, nullable=False)
    best_epoch = Column(Integer, nullable=False)
    training_time_seconds = Column(Float, nullable=False)
    model_parameters_path = Column(String, nullable=False)
    metrics_summary = Column(Text, nullable=False)  # JSON serialized metrics
    report_file_path = Column(String, nullable=False)
    created_timestamp = Column(DateTime, default=utc_now)

    # Relationships
    training_job = relationship("TrainingJob", back_populates="training_reports")
